/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MarketRouteImport } from './routes/market'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksTickerRouteImport } from './routes/stocks.$ticker'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksTickerRoute = StocksTickerRouteImport.update({
  id: '/stocks/$ticker',
  path: '/stocks/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/holdings': typeof HoldingsRoute
  '/market': typeof MarketRoute
  '/search': typeof SearchRoute
  '/stocks/$ticker': typeof StocksTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/holdings': typeof HoldingsRoute
  '/market': typeof MarketRoute
  '/search': typeof SearchRoute
  '/stocks/$ticker': typeof StocksTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/holdings': typeof HoldingsRoute
  '/market': typeof MarketRoute
  '/search': typeof SearchRoute
  '/stocks/$ticker': typeof StocksTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/account' | '/holdings' | '/market' | '/search' | '/stocks/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/holdings' | '/market' | '/search' | '/stocks/$ticker'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/holdings'
    | '/market'
    | '/search'
    | '/stocks/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  HoldingsRoute: typeof HoldingsRoute
  MarketRoute: typeof MarketRoute
  SearchRoute: typeof SearchRoute
  StocksTickerRoute: typeof StocksTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$ticker': {
      id: '/stocks/$ticker'
      path: '/stocks/$ticker'
      fullPath: '/stocks/$ticker'
      preLoaderRoute: typeof StocksTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  HoldingsRoute: HoldingsRoute,
  MarketRoute: MarketRoute,
  SearchRoute: SearchRoute,
  StocksTickerRoute: StocksTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
